[package]
name = "bacteria"
version = "0.0.4"
authors = ["hello@organism.org"]
description = "Bacteria: Strobe & Transcript Protocol"
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mohan = "0.0.21"
zeroize = "0.10"
rand = "0.6"
subtle = "2"
rand_core = { version = "0.4", default-features = false }

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand_chacha = "0.1"
hex = "0.3"